### ISSUE TITLE
Include .jar files in releases

### ISSUE THREAD

**Issue by odysseus654** [comixed/comixed-metadata-comicvine#13]
**Is your feature request related to a problem? Please describe.**

The installation instructions describe downloading a release and copying the included .jar file into the user's extension directory.  However only source code artifacts are included in the only release listed.

**Describe the solution you'd like**

A compiled release would be appreciated.

**Describe alternatives you've considered**

I will at a later date create a development environment so I can build my own artifacts from this.

**Comment by mcpierce** [comment]
@odysseus654  Thanks for reporting this, I hadn't realized the release bundle wasn't pushed. This should be fixed now. Please feel free to close this ticket if all is working correctly.

**Comment by odysseus654** [comment]
After realizing that you had changed the name of the key property, I was able to get this working again, thank you for the fast response :-)
